### ISSUE TITLE
Add possibility to install oersi-plugin

### ISSUE THREAD

**Issue by mirjan-hoffmann** [TIBHannover/wordpress-box#1]
https://gitlab.com/TIBHannover/oer/wordpress-oersi-plugin should be installed automatically via ansible

**Comment by mirjan-hoffmann** [comment]
@Edmondi-Kacaj Can you please tell me how to configure the oersi-plugin internally (in order to be able to configure it via ansible). I don't want to use the UI for this, but implement an automatic process.

**Comment by Edmondi-Kacaj** [comment]
Hello @mirjan-hoffmann 

I think this is not part of ansible, this must be the job of the plugin itself, I will create a default configuration for the plugin, and It will be automatically inserted, into the activation process, since also in a manual installation I think the default configuration must be added in order to work the plugin.

So I think the implementation in ansible it's already done, I will commit the changes after the daily, and then we can test it again. :)

**Comment by mirjan-hoffmann** [comment]
I think it should also be possible to update the configuration via ansible. This way everyone can use her/his own configuration and also use the ansible-scripts for production-deployments.

I will add the possibility to adjust the configuration via wp-cli in ansible
